name: GitHub Snake Game

# Grant the workflow write permissions to push to your repository
permissions:
  contents: write

on:
  # Run the workflow daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering
  workflow_dispatch:
  # Run the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animations with an oceanic dark theme
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: alphatasker
          outputs: |
            dist/github-snake.svg
            "dist/github-snake-dark.svg?palette=custom-oceanic-dark"
            "dist/ocean.gif?color_snake=deepblue&color_dots=#1b3a4b,#2e5266,#476d8a,#6581a0,#82a3b3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
